
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package alexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Suma = 2;
  public static final int Numero = 19;
  public static final int Leer = 12;
  public static final int Metro = 23;
  public static final int Proceso = 9;
  public static final int FinProceso = 10;
  public static final int Mientras = 16;
  public static final int Identificador = 20;
  public static final int Operador_Relacional = 5;
  public static final int FinMientras = 18;
  public static final int Operador_Asignacion = 6;
  public static final int Que = 15;
  public static final int Cadena = 21;
  public static final int Kilogramo = 24;
  public static final int EOF = 0;
  public static final int Hacer = 17;
  public static final int Por = 4;
  public static final int Escribir = 11;
  public static final int Repetir = 13;
  public static final int error = 1;
  public static final int Parentesis_C = 8;
  public static final int Menos = 3;
  public static final int Parentesis_A = 7;
  public static final int Hasta = 14;
  public static final int Number = 25;
  public static final int Pi = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Suma",
  "Menos",
  "Por",
  "Operador_Relacional",
  "Operador_Asignacion",
  "Parentesis_A",
  "Parentesis_C",
  "Proceso",
  "FinProceso",
  "Escribir",
  "Leer",
  "Repetir",
  "Hasta",
  "Que",
  "Mientras",
  "Hacer",
  "FinMientras",
  "Numero",
  "Identificador",
  "Cadena",
  "Pi",
  "Metro",
  "Kilogramo",
  "Number"
  };
}

